src/wfcomman.c
src/wfgoto.cpp
src/wfinit.c
src/winfile.h

per @rbeesley in https://github.com/Microsoft/winfile/commit/7185e43f5458f581f8de6ee40780ddf4affb15f7#commitcomment-28501075

revert Trie and add a comment

---

src/wfgoto.cpp

remove preprocessor directives and switch SetWindowLong for SetWindowLongPtr to enable x64 compatibility

enable goto with x64

---

.gitignore
src/GNUmakefile

Add makefile for mingw

---

src/GNUmakefile

add depend target for GNUmakefile

---

src/Winfile.vcxproj
src/res.rc
src/tbar.c
src/wfcomman.c
src/wfinit.c
src/winfile.c
src/winfile.exe.manifest
src/winfile.h

Changed the major version number or the application from 10 to 9. Minor version numbers remain unaffected.
Merged latest commits from master branch, as they are apparently known to not have compatibility issues with older releases of Windows.

Retro Branch Applicaton Version is now 9.0.1804.0

---

src/GNUmakefile
src/lang/res_ja-JP.rc

SUBLANG_XXX is defined in winnt.h
And I modified res_ja-JP.rc .

fix build on mingw

---

src/lang/res_en-US.rc
src/lang/res_he-IL.rc
src/lang/res_ja-JP.rc
src/lang/res_pl-PL.rc
src/lang/res_zh-CN.rc

This menu item seems useless in the popup. It is already available in the top menu items.

Removing About item from popup.

---

src/lang/res_pl-PL.rc
src/lang/winfile_pl-PL.dlg
src/origrc/winfile.pl-PL.rc

* Add translations of new dialog messages.
* Convert `src/origrc/winfile.pl-PL.rc` from Windows 1250 to UTF-8

Add missing Polish translations and fix original translation encoding

---

README.md

Minor Typo Corrections

---

src/lang/res_ja-JP.rc

Fixed Japanese translation.

---

src/wfcomman.c

This is to improve on the situation in #270 .
Since the Windows clipboard is multi-format, copy objects in forms to facilitate pasting (as files) as well as pasting (as text.)
Note this changes how `CheckMultiple` is used.  The existing code would only copy a single _file_ .  This change allows a single _file or directory_ .  I think this makes sense in general and verified that pasting a directory will copy as expected.

When copying, include text to path to enable pasting as strings

---

src/wfdirrd.c

Some junctions created by windows are not redirected when selected (because they are inaccessible). This looks like
In this very case the target (c:\users) of an inaccessible junction is shown, which is .... unexpected
The PR redirects junctions like this to their target if the target can be read:
Simply double click on 'Documents and Settings', to see the content of the redirected target
The change simply takes the target of DecodeReparsePoint() and feeds in to szPath and starts over with the WFFindFirst().

Redirect inaccessible Reparse Points

---

src/lang/res_tr-TR.rc
src/lang/winfile_tr-TR.dlg

Improves translations, removes ambiguities, makes the spelling more
in-line with the current Windows terminology.

Improve Turkish l10n

---

src/lang/res_de-DE.rc
src/lang/res_en-US.rc
src/lang/res_he-IL.rc
src/lang/res_ja-JP.rc
src/lang/res_pl-PL.rc
src/lang/res_tr-TR.rc
src/lang/res_zh-CN.rc

Added HotKey string "Ctrl+Shift Enter" to menu-bar

Added HotKey string "Ctrl+Shift Enter" to menu-bar

---

src/lang/res_de-DE.rc

Fix German text for New Window from #349

Fix German text for New Window

---

src/wfdlgs2.c

Search window immediatley opens after begin of search

Search window immediatley opens after begin of search

---

samples/addon/AddonSample.vcxproj
src/Winfile.vcxproj
tools/ExeView/ExeView.vcxproj
tools/FileSignatureInfo/FileSignatureInfo.vcxproj
tools/VerifyResources/VerifyResources.vcxproj

Prepare for release using internal Microsoft built pipeline, which requires 2019 toolset and some specific settings.
@schinagl, can you review?

Craigwi use 2019 toolset

---

README.md

Fixes for Readme.md so that it fits to most recent release
@podsvirov : Everthing correct?
@craigwims : What are the most recent locations for 'Latest build from master.... ' on Azzure

Release specific download locations

---

src/treectl.c
src/wfdirrd.c
src/wfdlgs.c
src/wfdrives.c
src/wfdrop.h
src/wfsearch.c
src/wfutil.c
src/winfile.c

This removes tab indentation from files that are 80%+ indented by spaces.  There are a handful of files that are predominantly tab indented, but this takes care of most of the remaining inconsistencies.

More tab to space conversions

---

build/Winfile.props

suggest using /O1 flag for XP builds
[NO_TRAIN]::

XP builds - use /O1 optimization

---

Package/Package.appxmanifest
nuget/winfile.nuspec
src/res.rc

Seems like a good time to prepare a new release.
This is my first time doing this, so apologies in advance for any bumps, particularly with Store and Chocolatey releases.  Getting signed binaries on Github looks straightforward.

Update winfile version

---

src/wfinit.c

This is to address #440 .
Winfile saves settings associated with each window.  Many of these settings are not global in nature, they are per-window.  When requesting a specific directory on the command line, the previous code would therefore revert to defaults.  This change uses the settings of the topmost window that had previously been saved, which is the behavior that would happen if a new window were created from a saved workspace.
At the same time though, the disconnect between saved workspace and a specific directory is still very pronounced.  Because opening winfile with a specific directory will not save settings automatically, there is still plenty of scope for confusing behavior.

Open command line windows with settings of topmost saved window

---

src/wfcomman.c

This is to address the issue reported by @DBJDBJ in https://github.com/microsoft/winfile/issues/100#issuecomment-383147012 .  If Goto targets a different drive, it updates internal state to refer to the new drive, including updating the drive toolbar; but the drive toolbar is not repainted so the user does not see this update.  (It can be seen by dragging Winfile off screen and back again.)
This happens because `SelectToolbarDrive` has gone out of its way to disable repaint.  There's an optimized repaint over in `SwitchDriveSelection`:
https://github.com/microsoft/winfile/blob/e3075d599a763c9ef86a0a612a83fd9b6976c243/src/wftree.c#L324-L333
...which seems like a necessary evil from the early 1990s; the approach in this PR is just to repaint the whole drive bar if anything changes (which it …

Repaint the drive window after changing drive selection in goto
