- src/res.rc
- src/wfcomman.c
- src/winfile.h
This PR adds a "Start Bash Shell" to menu, which opens Bash on Windows, if it's installed.
While I totally agree with the comments in #44 that it is better to make this configurable, I don't have enough Windows GUI knowledge to write a configuration dialog. So far I only implemented a menu item "Start Bash Shell", which launches `bash.exe` if it exists. I want to share this code so that, if you want, you can develop on top of this PR.
> Add Bash Shell support (partially fixes #44)

- README.md
This commit fixes an issue introduced in PR #95.
The link to the "Releases" page had a redundant https prefix, causing the link to be broken. The redundant prefer is removed and the link should work correctly.
> Fixed broken link introduced with PR #95

- src/Winfile.vcxproj
Addressed issue #102 by removing mincore.lib and replacing with version.lib. I was able to successfully build and test on Windows 10. I don't have a Windows 7 machine or VM available at the moment. It would be good if someone could verify the change on Windows 7 as well.
> Fix issue #102 Windows 7 issue with mincore.lib by using version.lib instead 

- src/res.rc
The application version has been updated from version 10.0.0.0 to version 10.0.1804.0. I've not updated the major or minor version; so it's still version 10.0 as of now. The 1804 signifies that it is the April 2018 code.
Since there is no automated versioning system implimented yet, this allows us to at least easily update the version without worrying about whether to increment the major or minor version.
Note: I originally wanted to go with something like 180418, (YYMMDD) to include the day. This way, whoever commits a code, they would just update the version number to reflect the date. Then it'd be super easy to tell which "build" one is runnign for troubleshooting reasons. But I went with just YYMM (1804) because we'd only need to increment the version at least once a month.
But I'm …
> App Version Updated to Version 1804

- src/Winfile.vcxproj
- src/res.rc
- src/winfile.c
- src/winfile.exe.manifest
> enable visual style on mingw

- src/wfgoto.cpp
Fixes #131 by simply ignoring reparse points when indexing.
> Don't index through reparse points in case they go in an infinite loop.

- src/lfn.c
Looks like WOW redirection on x64 causes LastError to be reset, and the directory enumerate code was expecting ERROR_ACCESS_DENIED not ERROR_INVALID_FUNCTION.  Note this is specific to x64.
~~(I'm not thrilled about how this works when FindFirstFile finds something that the filter wants to remove.  Previously LastError in this case seemed random, now it returns FALSE with LastError of zero.)~~
When filtering FindFirst will always call FindNext, and FindNext is the thing setting the error.  It also had the same WOW bug though.
> Don't return ERROR_INVALID_FUNCTION on x64 builds for enumerate errors (#135)

- src/winfile.h
I tried to compile latest WinFile with a project created by me and I got a crash immediately after the application was started: in my opinion, this happened because the pointers to WNet functions are not declared for using __stdcall calling convention.
After doing the fix described in this PR, the issue disappeared.
The bug could be also by-passed by forcing default calling convention to __stdcall, but in this way the code looks more correct.
Sincerely.
> Fix calling convention for WNet function pointers

- tools/ExeView/filllb.cpp
- tools/ExeView/init.cpp
- tools/ExeView/res.cpp
Fixing calls to SendMessage() that cast the last parameter to LONG, changing to LPARAM.
The one that was causing ExeView to crash at startup was in init.cpp, SendMessage with LB_SETTABSTOPS.
> Getting ExeView to run in x64

- src/spinlock.h
because the IntelliCode might yield errors C2039 and C3861
> added <stdexcept>

- README.md
The badge currently in the README points to `assets.windowsphone.com`, which no longer hosts the image. This changes the URL to use the `developer.microsoft.com` domain.
> Fix the "Get it from Microsoft" Badge in README.md

- GNUmakefile
GNU Makefiles often use standardized variable names to e.g. allow to
override default values. This allows us e.g. to issue following command
to cross-compile the project using 64-bit Cygwin without modifying the
makefile.
make -f GNUmakefile \
CC=i686-w64-mingw32-gcc \
CXX=i686-w64-mingw32-g++ \
WINDRES=i686-w64-mingw32-windres \
LDFLAGS+=-static
For more info see: https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html and https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#Catalogue-of-Rules .
> Modify GNU Makefile to use standard variables

- src/numfmt.c
- src/numfmt.h
- src/wfdos.c
- src/wfinfo.c
- src/winfile.h
This is to fix issue #257 .
GetDiskFreeSpaceEx returns unsigned 64 bit values; internally winfile is still using signed 64 bit values.
> Use GetDiskFreeSpaceEx to report larger amounts of free space

- src/winfile.c
ALT + ENTER does not show the properties dialog for root directories
But one can achieve this anyhow via right mouse on the root directory in the tree control by selecting 'Properties' from the context menu.
This change enables ALT + Enter on the root drive in the tree control aka left pane.
Maybe there is a good reason for the existing behavior, but I don't see the point. Maybe it did not work in older Windows versions, but from my naive point of view everything works nicely.
@craigwi: What is your opinion?
> ALT + ENTER does not show the properties dialog for root directories

- src/treectl.c
This is to fix #273 .  Based on the description that this occurs when "Directories Read" is displayed in the status bar and is gradually incrementing, this delay seems highly likely to be caused by `ScanDirLevel`.  This change removes that call unless VIEW_PLUSES is set, and updates the right arrow code to not depend on it.
When looking at the right arrow code, compare to how double click works.  This is handled in `OpenOrEditSelection`, which sends `TC_TOGGLELEVEL` back to `TreeControlWndProc`, which checks the current state, and if it's not expanded, sends `TC_EXPANDLEVEL` to itself.  The code in `TC_EXPANDLEVEL` calls `ExpandLevel` unconditionally whether there is anything known to be under the level or not.  So I believe/assert this must be safe/correct for right arrows too. …
> Allow right arrow expand without proactively recursively enumerating

- src/Winfile.vcxproj
This change:
- Removes /Gm which is deprecated and triggers a compiler warning using the 2017 compiler;
- Adds /MP which causes compilation to be performed in parallel.  Because all source files are in a single directory, msbuild invokes a single compiler instance for them all, so achieving parallelism requires asking the compiler for it.
> Enable parallel build and remove deprecated minimal rebuild

- src/wfdlgs.c
This is complimentary to #297 .  When view options change, regenerate the left pane.  This is the most heavyweight process, but view options won't change.
See also discussion at in #274 about this behavior.
> Heavyweight tree refresh after changing view options

- src/lfn.c
- src/treectl.c
- src/wfdirrd.c
This is to fix #268 .  Although it's not what the title says, looking closer at the screenshots, the concern is around seeing junctions in the left pane (which the user does not have access to), even though the setting for "Show Junction Points" is disabled.
This change leverages `dwReserved0` to identify the reparse tag, which is [now documented behavior](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataw) but has existed since reparse points were added in Windows 2000.  I followed the pattern of having the caller filter junctions, which is not optimal - with `dwReserved0` it should be possible to use `dwAttrFilter` for Junctions too, but that requires carefully scrubbing the code to ensure it's propagated.  Most of this change is about …
> When junctions are hidden, also hide from left pane

- src/wfcopy.c
Winfile follows reparse points during deletion and thus deletes linked content, which is not wanted. Currently there is no way of simply unlinking a reparse point. Explorer is aware of this. 
I would say this is a critical problem in Winfile, because it really deletes things, which you don't want to be deleted
Download ln.exe from https://schinagl.priv.at/nt/ln/ln64.zip and place it in the same directory as the below .bat file
Start [TestDeleteReparsePoint.bat](https://github.com/microsoft/winfile/files/8055166/TestDeleteReparsePoint.zip) from an administrative command prompt (or grant yourself the right to create symbolic links) in your e.g. temp directory.
It builds a structure like 
```
├───1
│   ├───iLib
│   │   ├───inc
│   │   └───src
│   ├───iLib_symlink (-> x:\sl\iLib )
│   │ …
```
> Do not follow Reparse Points during deletion and copy

- src/wftree.c
This is to fix #242 .  Note this is cosmetic and subjective, so it's completely fair if people think this not a change we want to make, although if there's a concern about the visual change, I think we should close #242 to clearly indicate this is not something to pursue.  Note the visual change depends a little on the Windows version; I agree with the screenshot in 242 that this works better with the "classic" UI, although it's less clear on a more modern UI that it's visually superior.
In terms of implementation, note that the code has a frame window; within that there's a child which is the MDIClient; and within that are individual windows.  Those windows are created via `WM_MDICREATE` which doesn't specify extended styles.  So this change works by setting extended styles during …
> Display child windows with sunken borders for purely cosmetic reasons

- src/wfdirrd.c
The left pane implodes to the root drive if one clicks on a dead Reparse Point
Download ln.exe from https://schinagl.priv.at/nt/ln/ln64.zip and place it in the same directory as the below .bat file
Start [TestDeadReparseImplode.bat](https://github.com/microsoft/winfile/files/8102923/TestDeadReparseImplode.zip) from an administrative command prompt (or grant yourself the right to create symbolic links) in your e.g. temp directory.
It builds a structure like
```
└───dest
└───sl
├───iLib_dead
└───iLib_symlink
```
Navigate to x:\dest\sl and double click on iLib_symlink. The left pane does not implode to the root as the original version does.
There is one little change in CreateDTABlockWorker(), which deals with the failing WFFindFirst and checks if the item was a dead Reparse Point
> Left Pane implodes on dead Reparse Points

- src/treectl.c
- src/wfdirrd.c
- src/wfsearch.c
This is addressing the feedback in #304 :
1. Use ATTR_SYMBOLIC | ATTR_JUNCTION to test whether something is a link, since a reparse point is not always a link; it could be a virtual git file, store app, onedrive placeholder, all kinds of things;
2. Use braces around if conditions.  There was a commit for this in the original PR but it wasn't included in the merge.
> Incorporate PR feedback for link icon change

- src/treectl.c
- src/treectl.h
- src/wffile.c
In the aftermath of #308 I stumbled about one detail we missed:
After (un)compress on a symbolic link the symlink icon is not shown anymore.
Download ln.exe from https://schinagl.priv.at/nt/ln/ln64.zip and place it in the same directory as the below .bat file.
Start [TestCopyReparsePoint.bat](https://github.com/microsoft/winfile/files/8430378/TestCopyReparsePoint.zip)  from an administrative command prompt in your e.g. temp directory. 
It builds a structure like
```
├───1
└───sl
├───iLib
│   ├───inc
│   └───src
├───iLib_symlink
│   ├───inc
│   └───src
└───zzz
```
Select sl/iLib_symlink and choose from the menu File/(Un)Compress. The symlink icon of sl/iLib_symlink is shown properly contrary to the original. 
There are two locations in the source where the attributes are fetched directly …
> Symlink Icons are not shown after (un)compress

- src/treectl.c
When copying a tree above a selection the selection is way too below after the copy 
See [this short video](https://user-images.githubusercontent.com/7418603/163217428-fbf7e5cb-6cde-4467-b36a-593def056ce8.mp4)
The selection after copy is on 'IterateLPXDTA' which is wrong. It should be 'sl'. I checked a one year old version of Winfile and it is also there. So no side-effect of recent changes
Download ln.exe from https://schinagl.priv.at/nt/ln/ln64.zip and place it in the same directory as the below .bat file.
Start [TestCopyReparsePoint.bat](https://github.com/microsoft/winfile/files/8430378/TestCopyReparsePoint.zip)  from an administrative command prompt in your e.g. temp directory.
It builds a structure like
```
├───1
└───sl
├───iLib
│   ├───inc
│   └───src
├───iLib_symlink
│   ├───inc
│ …
```
> Wrong position of selection after copy

- src/wfdirrd.c
- src/wfsearch.c
Search stops with error when it comes along an illegal reparse point. (This is not a dangling reparse point, but an illegal!)
An illegal reparse point contains illegal reparse data.
Basically it is an extension of the error handling in two places, which deals with error codes that come from illegal reparse data.
I accidentally stumbled across such a situation, when the search for a file stopped with the message 'The data present in the reparse point buffer is invalid.` This is ERROR_INVALID_REPARSE_DATA
Then I started to create illegal reparse points via the debugger with an extra tool, and found ERROR_CANT_ACCESS_FILE to be malicious too. Both are handled now.
> Search stops with error when it comes along a broken reparse point.

- src/wfcopy.c
- src/wfdir.c
- src/wfdirsrc.c
One wants to create a copy of a file/directory in the very same directory. 
Dragging a file/directory onto the empty space in the file-pane does nothing currently.
With this change one can drag an already existing file/directory into the empty space of the file pane and an item with the ' - Copy' is created.
E.g. File.txt -> 'File - Copy.txt'
Lets have a [live look
](https://user-images.githubusercontent.com/7418603/162826074-d0f83ec9-a622-48bb-b437-c7f10e33225b.mp4
)
I starts in wfdirsr.c: 1049, where normally a drop on the same directory was blocked.
Enabling this only for 'copy' (fShowSourceBitmaps == TRUE) brings us to wfcopy.c, which is extended once for files and once for directories.
This PR intentionally only works in the same directory.
There is no Copy (n) algorithm implemented …
> One Level file '- Copy' pattern

- src/tbar.c
Do not show the 'permissions' icon in the taskbar with this branch, because it is not available with W7++ anymore.
The coding is still in, because other branches which might target W2K & WXP do have the functionality
> Do not show the permissions icon in the taskbar on new installations

- src/wfdir.c
The directory pane suffers from some weird behavior of the list box. If you press _ it selects from anchor to caret:
- Run [wrong_selection.zip](https://github.com/microsoft/winfile/files/8682133/wrong_selection.zip). It creates a few almost empty files in a directory.
- Select the file installservices.exe
- Start typing 'i' 'n' 't' '\_'
You will end up with this
But all you wanted was to type 'int_' have 'int_bla.dll' selected
Well this was hard to find out, but it seems the used listbox in Winfile from comctl32.dll has a virtual key behind '\_', which selects all items from anchor to caret.
In wfdir.c:603 @ WM_CHARTOITEM at the return of the 'case', the actual position is returned with respect to the typed character.
If e.g. anchor = 2, and caret = 2, and this case statements returns 5, …
> Wrong selection when typing _

- src/tbar.c
I tried to use the customize toolbar feature, and found it had a subtle assumption that was modified in #324 .
`GetAdjustInfo` copies the final toolbar item (`tbButtons[TBAR_BUTTON_COUNT-1]`) and uses it to fill in all undefined fields when populating the customize dialog.  #324 changed the final button to be a separator, so everything in the customize dialog has the separator flag set.  This means all of the strings and icons are missing in the dialog, and attempting to move any icon ends up replacing the icon with a separator, so it's invisible and inaccessible.
> Fix toolbar customize

- src/res.h
- src/tbar.c
- src/wfcomman.c
- src/wfinfo.c
- src/wfinit.c
- src/winfile.h
Net Share not working. The share icon in the toolbar was always grayed out
Winfile used an API to share network resources from ntlanman.dll, which is not available anymore with Windows7/10
Changed it to use ShowShareFolderUI() from Ntshrui.dll. Works. 
Unsharing is the problem. How does one open this dialog
Which is invoked through explorer via
Any ideas? @craigwi , @malxau can you have a look behind the scenes on how explorer does this? Is it in Shell32.dll ? Or where is it?
I was not able to google this at first hand, maybe you are faster on this
> Netshare/NetUnShare Button always grayed out

- src/tbar.c
- src/treectl.c
- src/wfassoc.c
- src/wfchgnot.c
- src/wfcomman.c
- src/wfcopy.c
- src/wfdir.c
- src/wfdirrd.c
- src/wfdirsrc.c
- src/wfdlgs.c
- src/wfdlgs2.c
- src/wfdlgs3.c
- src/wfdrives.c
- src/wfdrop.c
- src/wffile.c
- src/wfgoto.cpp
- src/wfinfo.c
- src/wfinit.c
- src/wfloc.c
- src/wfmem.c
- src/wfprint.c
- src/wfsearch.c
- src/wftree.c
- src/wfutil.c
- src/winfile.c
This is mainly casts to prevent x64 compiler warnings.  I looked at each case manually, mainly just preserving existing behavior.  Although it touches quite a bit, there's really a handful of patterns:
1. It looks like the code was bulk converted to use GetWindowLongPtr rather than GetWindowLong.  That implies truncating a 64 bit return value.  GetWindowLongPtr is needed for pointers or handles, but isn't needed for 32 bit values.  Nonetheless this change preserves them and casts the result, because I'll bet this conversion happened due to some other overzealous warning or analysis suggesting GetWindowLong isn't safe in 64 bit code.
2. There is arithmetic on 32 bit control IDs to map to extensions.  We shouldn't have more than 4 billion extensions.
3. SetStatusText can take either a …
> Fix x64 warnings

- src/wfdlgs2.c
Renaming a directory with . in it assumes the characters behind . are an extension, and does not select them
Start   [TestRenameSelectiont.zip](https://github.com/microsoft/winfile/files/8720358/TestRenameSelectiont.zip) from an administrative command prompt in your e.g. temp directory. 
In the directory or file pane navigate to bla.000.000.000 and press F2. All characters are selected now
Do this also for bla.000.000.000 - symlink. Also all characters are selected
When selecting bla.000.000.000.dll, which is a file, only the characters before the extension are selected as in the previous version.
> Rename shall select all characters when it is a directory and contains a dot

- tools/VerifyResources/VerifyResources.cpp
VerifyResources is attempting to navigate controls within an in-memory dialog template, and needs to know the number of bytes within each control.  Controls can include optional additional creation data.  When skipping this data, it's important to skip not just the data but also the field indicating the number of bytes of creation data; this is skipped when no data is present, but was not skipped when additional data is present.  This results in VerifyResources being in the wrong offset and interpreting localized strings as control data, causing it to complain about resource mismatches continually.
> Update VerifyResources to handle custom control creation data

- src/wfutil.c
With #290 TypeAhead was fixed, but we all overlooked one use-case
Assume you have the following files in a directory
```
as
bla
san
system
syxsser
zzz
```
The [attached .bat file](https://github.com/microsoft/winfile/files/8866981/TypeAHead.zip) creates such a situation.
- Select 'bla' in the right pane
- Type 's' 'y' 's'
- The cursor is on 'syxsser' which is **not correct**. It should be on 'system'
With #290 we overlooked, that only *consecutive same* characters shall move the cursor ahead by one. The #290 solution also moves ahead by one, if any character typed within a word is the same as the first, but other characters are in between.
I now cross checked the fixed behavior with explorer and it is exactly the same.
> TypeAhead Fix

- README.md
- src/wfgoto.cpp
- src/wfinfo.c
- src/wfinit.c
- src/winfile.h
The Goto Cache had a few little problems
* It followed all reparse points, which could drive it into a reparse - loop. 
* Items were enumerated many times when they were behind reparse points
* The punctuation was limited to \<blank\> See #296
* The punctuation could not be configured
* The punctuation is now extended to "- _."
* The punctuation can be configured via Winfile.ini[Settings]GotoCachePunctuation
* The Goto Cache now only follows 
**so called 'outer' reparse points, but drops so called 'inner' reparse points, because these files are anyhow reached via normal file enumeration.
** Onedrive. This PR also works for OneDrive and opposite to #132 has no limitations.
What is a 'inner'/ 'outer' reparse point: 
* With respect to a root, e.g. c:\foo a reparse point is called 'inner' if …
> * Goto Cache Improvements 

- README.md
Change Wikipedia link from https://en.wikipedia.org/wiki/File_Manager_(Windows) to https://en.wikipedia.org/wiki/Windows_File_Manager
> Update Wikipedia link in readme

- src/wfdlgs.c
- src/wfgoto.cpp
- src/winfile.h
Save CachedPath and GotoCachePunctuation on exit, because if it lacks from the .ini file, it has to be created somehow.
I missed this once I did those extensions to winfile.ini in #293 and #329
It is needed because otherwise the *initial* .ini file entries must to be created manually, which is cumbersome and error prone.
With this change the .ini entries are there with a default value, and the user simply can change just the value.
> Save CachedPath and GotoCachePunctuation

- src/treectl.c
- src/wfcomman.c
- src/wfdrives.c
- src/winfile.h
FS_GETFILESPEC caused buffer overflows on too small buffers in 3 places:
wfcomman.c
wfdrives.c
FS_GETFILESPEC was called with e.g. MAXFILENAMELEN, but the start of the WCHAR was moved back by lstrlen(szPath), thus causing a buffer overflow.
treectl.c
FS_GETFILESPEC was called correctly but when this was executed close to 256 chars it failed in getting the filespec, because the string was truncated @MAXFILENAMELEN
- If you follow e.g the path from OpenOrEditSelection() it begins with allocating szPath with MAXPATHLEN+2. 
- In wfcomman:674 CreateDirWindow() is called with szPath, which still is fine, 
- in wfcomman.c:554 the already partially filled szPath is taken, and handed over to FS_GETFILESPEC with MAXFILENAMELEN. 
- FS_GETFILESPEC is now allowed to append MAXFILENAMELEN to szPath (it …
> FS_GETFILESPEC caused buffer overflows on too small buffers in 3 places:

- src/wfgoto.cpp
Currently Winfile only shows 10 results from the Goto Cache search after CTRL-G
This is many times not enough, so increased it
> Show more than 10 results from goto cache

- src/wfgoto.cpp
- Added PageUp/PageDown for goto-dialog navigation. Needed because with many items in the listcontrol one wants to quickly go through the cache hits.
- Removed Cursor up/down key wrap around, because the top/end can reached with VK_HOME/VK_END, thus no need for wrap around
> PageUp/Down navigation for CTRL-G dialog

- src/lang/res_zh-CN.rc
Replace some misused `zh-Hant` translations with `zh-CN` ones. Mentioned in #352 earlier but some bugs leaked into the [final commit](https://github.com/microsoft/winfile/commit/4a689ad).
In short, a simple replacement: `符號鏈接`→`符号链接` (Symbolic link), `硬鏈接`→`硬链接` (Hard link), `目录连接点`→`目录联接` ((Directory) junctions) (from Windows cmdlet `mklink`), and restructuring of some sentences.
> Fix translation mistakes of zh introduced in #352

- src/Winfile.vcxproj
This is to remove `#define` values that were carried forward from the Windows build environment and are not used.  These have mostly already been removed from C code but were still used in RC compilation.  I verified they are not used in winfile or in the SDK headers that it includes.
Note this changes `_M_IX86` to `_M_IX64` for x64 builds.  These should normally be defined by the compiler but are explicitly defined here.  It's not safe to get these wrong since it may result in incorrect structure definitions.  Since this is specific to the resource compiler it doesn't seem like a big risk, but still.
> Remove unused defines

- tools/VerifyResources/VerifyResources.cpp
This allows VerifyResources to compile as x64, and to verify x64 binaries.  It looks like the resource file format is always 32 bit aligned, not pointer aligned, so the logic is identical for binaries of different bitness.
> VerifyResources on 64 bit systems

- src/wfdir.c
Show <SYMLINK> for file symlink and not 0 bytes size
> Show <SYMLINK> for file symlinks

- GNUmakefile
- src/winfile.h
This fixes two minor things so clang can compile cleanly:
- Explicitly list all libraries being linked against to avoid unresolved externals
- Change the header brace style for a header that's included in the source tree that's not in the include path
> Fixes for clang

- src/treectl.c
- src/treectl.h
- src/wfassoc.c
- src/wfcomman.c
- src/wfcopy.c
- src/wfcopy.h
- src/wfdir.c
- src/wfdirrd.c
- src/wfdlgs.c
- src/wfdlgs2.c
- src/wfdlgs3.c
- src/wffile.c
- src/wfinfo.c
- src/wfinit.c
- src/wfmem.c
- src/wfsearch.c
- src/wftree.c
- src/wfutil.c
- src/winfile.h
Compiling with clang generates some new warnings.  One of these is the use of the `register` keyword.  As far as I know and have been able to find out, this has been ignored by all 32 bit and 64 bit compilers.  The winfile code appears to depend on this keyword being ignored, because it includes this keyword on parameters used by callback functions where the calling convention is defined by the operating system.
The x64 calling convention uses four registers for the first four parameters and has more registers available for locals, which has rendered this keyword more thoroughly obsolete.
> Remove register keyword which is obsolete

- src/lang/res_zh-CN.rc
- src/lang/winfile_zh-CN.dlg
Try to make strings friendly to readers.
This is an example to demonstrate the use of mechanisms provided by #388. This is a rough, personal opinion, based on previous practice of ja-JP.
- `IDS_KK_RENAMEFROMSTR` and `IDS_KK_RENAMETOSTR` is translated like ja-JP (Original name / Rename to), instead of single `From` in English.
- Verbs are added in all other `IDS_KK_*TOSTR`.
- Dialog controls are resized to fit.
> Use IDS_KK_ strings in zh-CN.

- src/lang/res_de-DE.rc
- src/lang/res_en-US.rc
- src/lang/res_he-IL.rc
- src/lang/res_ja-JP.rc
- src/lang/res_pl-PL.rc
- src/lang/res_tr-TR.rc
- src/lang/res_zh-CN.rc
This is after encountering that `Alt+F`, `X` no longer exits, because `X` is double-assigned between "Open With Explorer" and "Exit."  In `en-US`, `Alt+F`, `X` is a very established UI pattern for pull down menu based applications.
In the File menu, there were 24 items allocating letters for shortcuts, out of a 26 character alphabet, so there's really no more room to move in terms of assigning letters.
This change moves four items into a submenu, which frees up some letters for allocation and allows those items to have hotkeys that more naturally maps to their function.  It uses `Alt+F`, `.` to access the submenu, which I'm not happy about, but this results from the same issue it's trying to fix (the menu is so large that natural hotkeys can't be allocated.)  In English, none of the …
> Move start options to a submenu to avoid hotkey overloading

- src/lang/res_de-DE.rc
- src/lang/res_en-US.rc
- src/lang/res_he-IL.rc
- src/lang/res_ja-JP.rc
- src/lang/res_pl-PL.rc
- src/lang/res_tr-TR.rc
- src/lang/res_zh-CN.rc
- src/res.h
- src/wfdlgs2.c
Continuing from #400 .  This is a crude change to make the `Other:` text localizable.  For `en-US` I changed it to be a bit more descriptive, which is built on the assumption that the dialog will be large enough to accommodate it.
Note the current directory at the top of the dialog has some nice logic in `SetDlgDirectory` to truncate from the middle if it doesn't fit.  It would be really nice to do something similar here, but this text can contain an arbitrary number of components.  Also note that the current dialog resource specifies this text to be on a single line only, presumably because splitting lines based on spaces in paths wouldn't create a "natural" flow for paths.
I'm tempted to make the dialog resource multi-line, use one line per drive here, and use the logic in …
> Make 'Other:' text in MOVECOPY dialog localizable

- src/lfn.c
- src/treectl.c
- src/wfcomman.c
- src/wfcopy.c
- src/wffile.c
- src/winfile.h
This PR aims to build upon schinagl's earlier work in #409 and #406 .
In those discussions, the remaining issue was a case where links could be created as hidden, which would cause the left pane to be updated to contain the link (when it should be hidden.)
To summarize, three options were discussed to address it:
1. Avoid creating junctions/symlinks as hidden.
2. If they need to be created as hidden, do this before updating the UI, then have the UI check file attributes and decide what to include.
3. Leave the attribute update where it is today, and have the attribute update also update the UI, meaning that new links would be inserted and then removed when they become hidden.
This PR takes the first approach, because the behavior of Winfile here seems inconsistent with mklink and was …
> Refresh tree on junction or directory symlink creation

- src/wfutil.c
`TC_SETDRIVE` currently takes three boolean values encoded into `wParam` and an optional path in `lParam`.  If `lParam` is `NULL`, it looks up the directory from `FS_GETDIRECTORY`.
Between `original_plus` and the first 10.0 release, a change was made in `TC_SETDRIVE` that will update the selection without a refresh if the value supplied in `lParam` can be found in the existing tree.  In some cases, such as the View File Types dialog, `TC_SETDRIVE` is invoked with a `NULL` `lParam`, which causes a full refresh to occur.  In others, including `RefreshWindow`, `lParam` is supplied as a directory, which has the effect of suppressing any refresh.
This change modifies `RefreshWindow` to not supply `lParam` as a way to cause the refresh to happen.  The previous code was calling `FS_GETDIRECTORY` …
> Make the refresh menu item refresh the left pane

- Package/Package.appxmanifest
This is to fix #292 .  WinFile is a Desktop app and shouldn't appear on non-Desktop devices that support Universal binaries.  I can't test how the store will really behave until it's uploaded, but the docs suggest listing only a Desktop family is the way to express this.
> Don't mark Winfile as Universal since it can only run on Desktop systems

- .gitignore
- build/Winfile.default.props
- build/Winfile.props
- src/Winfile.vcxproj
- src/lfn.c
- src/tbar.c
- src/wfcomman.c
- src/wfdirrd.c
- src/wfinit.c
- src/wfloc.c
- src/wfutil.c
- src/winfile.h
Ever since this code was released, one of the most common things people do is backport to older systems.  There's been a few unofficial forks to do this, and one official branch in this repo.  What appears to happen each time though is people start from `master` then backport, as opposed to starting with an older build system then applying current changes.  Given that this seems to be a trend, it makes sense to just merge the changes needed for older systems into `master` so these backports are either unneeded or are substantially simpler.
The changes here target `v141_xp`; going older than XP with a Microsoft compiler would require Visual Studio 2008 or earlier and I think would require much more dramatic build system changes.  If the goal is just XP, the there's not much point using an …
> XP build based on v141_xp

- build/Winfile.props
These days there aren't many pre-SSE2 CPUs floating around, and it's basically a requirement for Windows 7 and up.  On XP, the base requirement is a Pentium 1 (not even Pentium Pro.)  WinFile could require a newer CPU than XP, but these instructions seem to be of limited value to it anyway, so there doesn't seem to be a good reason to stick with the SSE2 compiler default.
I dumped out the assembly from this and verified that `cmov` instructions are only used under runtime checks.  They're still used conditionally in `strchr` and `strrchr` operations.
> Compile XP builds for XP CPUs (aka, no SSE)

- src/lang/res_de-DE.rc
- src/lang/res_en-US.rc
- src/lang/res_he-IL.rc
- src/lang/res_ja-JP.rc
- src/lang/res_pl-PL.rc
- src/lang/res_pt-PT.rc
- src/lang/res_tr-TR.rc
- src/lang/res_zh-CN.rc
- src/res.h
- src/wfcomman.c
This is for #245 .  Shift+exit currently saves settings, but it's not obvious to anyone that it does, so it doesn't seem to hurt to have an explicit option.
My biggest concern with this is the name - "Settings" as in things in the Options menu are saved immediately.  This option is about saving open window locations.
> Add an explicit save settings to make shift+exit behavior more discoverable

- src/wfinit.c
- src/wfutil.c
- src/winfile.h
This is to fix #266 .
Some (arbitrary) choices that try to guess what a user would want in this situation:
- Only one directory can be specified on the command line.  If the first argument matches a directory, it is opened, and subsequent arguments are ignored.  If it's not a directory, the previous execute flow is used.
- Any saved windows are not opened if a directory is specified.
- That directory is opened maximized, since there can only be one.
- When opened in this way, Winfile will not automatically save settings on exit, even if that is the user's preference.  This can be toggled, or an explicit save can be triggered.
> Allow user to open a single directory on the command line

- src/wfcomman.c
- src/wfdlgs2.c
- src/wfinfo.c
- src/wfinit.c
- src/wfutil.c
- src/winfile.h
This started as a change to address #187 by constructing fully specified paths to system DLLs.  KnownDLLs already mitigates this type of attack, but it's good to be explicit.
This does not address addons; those seem like less of a security issue since an attacker would need to modify Winfile.ini to refer to one, and if they can do that, they probably already have access.  About the most sinister thing I can think of is code running in user context that believes the user will elevate Winfile, so modifying Winfile.ini allows for EOP; but doing that can be done without DLL planting.
Note, although it seems moot, that Undelete was building a system path then ignoring it (which is what made me ask #432 .)  Looking at the history of this code, I think it started as a performance optimization - …
> Initial conversion to LoadLibrary from system directory

- nuget/winfile.nuspec
As part of submitting a new release, Chocolatey issued a handful of warnings.  These weren't fatal to the release, but seem good to address before the next submission.  Most of them are around nuspec schema changes that didn't exist when the nuspec was written.
> Updates to nuspec based on previous choco submission

- build/Winfile.props
- src/treectl.c
- src/wfassoc.c
- src/wfcopy.c
- src/wfdir.c
- src/wfdrives.c
- src/wfinfo.c
- src/wfutil.c
As part of generating an official build, one warning was issued for not using SdlCheck (see https://learn.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=msvc-170 .)  Enabling this has the effect of enabling use of uninitialized pointer local variables, and most of this change revolves around that.  The general pattern seems to be Winfile using two locals, one which is initialized if a second is set, then later consumed if the second is set.  The compiler is not smart enough to understand that whenever it is used, the local will be initialized.  The changes here have the effect of suppressing the compiler warning, although any use of the local where it hasn't been initialized with the correct value will still be incorrect.  About the best thing these …
> Enable SdlCheck and fix warning for use of uninitialized pointer value

- src/wfassoc.c
I encountered a crash trying to use the associations feature without being elevated:
1. Add a new file type
2. At the bottom of the dialog, associate the new type with an extension that is already associated with a different type
3. Click ok.  The registry updates fail.
What's happening:
The association logic has a "global" data structure tracking file types and extensions.  When a new file type is being added, a new `FILETYPE` structure is allocated prior to opening the dialog (it is passed to `AssociateFileDlgProc` via `DialogBoxParam`.)  Adding the extension in the child dialog (in `AssociateFileDlgExtAdd`) causes the "global" extension to be linked to the new file type.  When clicking Ok, `AssociateFileWrite` calls `FileTypeWrite` to persist the new file type, then loops through …
> Fix crash modifying file associations

- src/wfgoto.cpp
- src/wfinit.c
Specifying a relative path on the command line when opening winfile causes it to crash (which is quite embarassing.)
Unsurprisingly, many pieces of code assume they're dealing with a fully specified path.  Winfile takes the first char and uses it to index into drive arrays.  If the first char is not a drive letter, it can end up referencing memory that is not within its drive array.
Looking around, I saw three similar places, although there may be more:
1. The new code to open a directory specified on the command line passed the user's string verbatim when opening a window, causing '.' to be treated as a drive letter.
2. The INI reading code called `CheckDirExists` which takes the first char and calculates a mod of 32 to determine the drive letter.  Characters like '.' become 'N' which is …
> Convert relative paths to absolute in initial directory, INI file reading and goto

- src/wfgoto.cpp
- src/wfinit.c
- src/winfile.h
This is to address the original issue in #100 .  In the previous code (and after this, still default code), hidden and system directories are not enumerated.  This means any subdirectories under a hidden/system directory will not be cached.
This PR adds a UI-less `winfile.ini` option to include hidden and system directories, including their children.
> Have a hidden option for goto to cache hidden and system subtrees
